[[main]]
    # Top-level menu entry
    identifier = "about_me"
    name = "About Me"
    url = "/about/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 4

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8

[[main]]
    identifier = "project-type"
    name = "Project Types"
    url = "/project-types/"
    parent = "explore"
    weight = 9